name: flutter_moviesliders
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # provider
  provider: ^4.1.3
  # network requests
  http:
  # local storage (used to store dark-mode)
  shared_preferences: ">=0.5.7+3 <2.0.0"
  # dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  # firebase auth
  firebase_auth: ^0.16.1
  # (used in sign in)
  google_sign_in: ^4.5.1
  # (used in sign in)
  apple_sign_in: ^0.1.0
  # firebase (real-time database)
  firebase_database: ^3.1.6
  # Google Analytics (dependency for the FlutterFire plugin)
  firebase_analytics: ^5.0.2
  # Charts
  charts_flutter: ^0.9.0
  # Connectivity (used for testing internet connection)
  connectivity:
  # Render HTML (used for privacy policy)
  flutter_html: ^1.0.0
  # auto_size_text 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons: # https://pub.dev/packages/flutter_launcher_icons
  # COMMAND: flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "Logo/flutter.moviesliders.logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - Logo/Icon-App-40x40@3x.png
    # - assets/images/home-1.jpg
    # - assets/images/home-2.jpg
    - assets/images/flutter.moviesliders.launchimage.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
